config/routes.rb
Rails.application.routes.draw do
  resources :chats do
    resources :messages, param: :chat_id
  end
  get "chat_users/create"
  get "messages/create"
  get "chats/show"
  mount_avo
  devise_for :users, path_names: { sign_in: "login" }
  namespace :api do
    namespace :v1 do
      resource :profile, only: [ :show, :update ]
    end
  end
  get "follows/create"
  get "follows/destroy"
  get "likes/create"
  get "likes/destroy"
  get "comments/create"
  get "comments/destroy"
  resources :posts do
    resources :subscribers, only: [ :create ]
  end
  root "pages#home"
  resources :articles, only: [ :index, :show, :new, :create, :edit, :update ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    validates :description, presence: true
end
# it has builtin setter and getter

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :chat_users
    has_many :users, through: :chat_users
    has_many :messages, dependent: :destroy
end

app/models/chat_user.rb
class ChatUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable, dependent: :destroy

  validates :content, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  # prevents a user from following another user more than once
  validates :follower_id, uniqueness: { scope: :followed_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/post.rb
class Post < ApplicationRecord
  include Notifications

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many_attached :media
  has_rich_text :description
  validates :content, presence: true
  validates :inventory_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates :name, presence: true, uniqueness: { case_sensitive: false }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
    has_many :chat_users
    has_many :chats, through: :chat_users
    has_many :messages, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    before_action :authenticate_user!
    def show
        # byebug
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new # Initialize a new article object
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        puts @article.inspect # Debugging line to check the article object
        if @article.save
          flash[:notice] = "Article was successfully created." # Set a flash message
          redirect_to @article # Redirect to the show page of the article
        else
          render :new # Render the new template again if save fails
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title, :description))
          flash[:notice] = "Article was successfully updated."
          redirect_to @article
        else
          render :edit
        end
    end
end

app/controllers/avo/articles_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
class Avo::ArticlesController < Avo::ResourcesController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_users_helper.rb
module ChatUsersHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

 <% if @article.errors.any? %>
   <h2>The following errors prevented the article from being saved</h2>
   <ul>
     <% @article.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
 <% end %>

 <%= form_with(model: @article, local: true, data: { turbo: false }) do |f| %>
   <p>
     <%= f.label :title %><br/>
     <%= f.text_field :title %>
   </p>
 
   <p>
     <%= f.label :description %><br/>
     <%= f.text_area :description %>
   </p>
 
   <p>
     <%= f.submit %>
   </p>
 
 <% end %>

app/views/articles/index.html.erb
<h1>Showing article details</h1>
 
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Placeholder</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <td>Placeholder</td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<% if @article.errors.any? %>
   <h2>The following errors prevented the article from being saved</h2>
   <ul>
     <% @article.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
 <% end %>
 <%= form_with scope: :article, url: articles_path, local: true, data: { turbo: false } do |f| %>
   <p>
     <%= f.label :title %><br/>
     <%= f.text_field :title %>
   </p>
 
   <p>
     <%= f.label :description %><br/>
     <%= f.text_area :description %>
   </p>
 
   <p>
     <%= f.submit %>
   </p>
 
 <% end %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
 
 <p><strong>Title: </strong><%= @article.title %></p>
 <p><strong>Description: </strong><%= @article.description %></p>